-- Japan Life Server: authentication + manual approval
-- Owner account: bomsronthai@gmail.com
-- Run this in a new Supabase project's SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  role text not null default 'player'
    check (role in ('owner','admin','player')),
  status text not null default 'pending'
    check (status in ('pending','approved','rejected','suspended')),
  approved_at timestamptz,
  approved_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.patch_releases (
  id bigint generated by default as identity primary key,
  version text not null unique,
  manifest_url text,
  patch_url text,
  sha256 text,
  size_bytes bigint,
  status text not null default 'draft'
    check (status in ('draft','published','retired')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists profiles_status_idx on public.profiles(status);
create index if not exists patch_releases_status_idx on public.patch_releases(status);

create or replace function public.is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'owner'
      and status = 'approved'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id, email, role, status, approved_at
  )
  values (
    new.id,
    lower(new.email),
    case
      when lower(new.email) = 'bomsronthai@gmail.com' then 'owner'
      else 'player'
    end,
    case
      when lower(new.email) = 'bomsronthai@gmail.com' then 'approved'
      else 'pending'
    end,
    case
      when lower(new.email) = 'bomsronthai@gmail.com' then now()
      else null
    end
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.patch_releases enable row level security;

drop policy if exists "profile self read" on public.profiles;
create policy "profile self read"
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_owner());

drop policy if exists "owner update profiles" on public.profiles;
create policy "owner update profiles"
on public.profiles for update
to authenticated
using (public.is_owner())
with check (public.is_owner());

drop policy if exists "approved users read published patches" on public.patch_releases;
create policy "approved users read published patches"
on public.patch_releases for select
to authenticated
using (
  status = 'published'
  and exists (
    select 1 from public.profiles p
    where p.id = auth.uid()
      and p.status = 'approved'
  )
);

drop policy if exists "owner manages patches" on public.patch_releases;
create policy "owner manages patches"
on public.patch_releases for all
to authenticated
using (public.is_owner())
with check (public.is_owner());

-- Important: do not expose service/secret keys in the APK or browser.
